<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>rel</string>
	</array>
	<key>name</key>
	<string>Relish</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>begin</key>
			<string>^""" *$</string>
			<key>end</key>
			<string>^""" *$</string>
			<key>name</key>
			<string>comment.block.relish</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(//).*$\n?</string>
			<key>name</key>
			<string>comment.double-slash.relish</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.relish</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>support.other.relish</string>
				</dict>
			</dict>
			<key>match</key>
			<string>\b(origin|artifact|package)\b(.*)</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>\b(import)\b</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.relish</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(^\W*$)</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>captures</key>
					<dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>keyword.relish</string>
						</dict>
					</dict>
					<key>match</key>
					<string>[a-z1-9/_]*( (as) [a-z1-9]*){0,1}</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(if|elif|else|while|for|break|continue|of|as|go|func|in)\b</string>
			<key>name</key>
			<string>keyword.control.relish</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b([A-Z]|[A-Z][A-Z0-9_]*[A-Z0-9])\b</string>
			<key>name</key>
			<string>constant.other.relish</string>
		</dict>
		<dict>
			<key>match</key>
			<string>[a-z][a-z0-9]*([A-Z][a-z]+[a-z0-9]*)*</string>
			<key>name</key>
			<string>storage.type.function.relish</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#string</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#multiline_string</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#numeric</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#datatype</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>bracket</key>
		<dict>
			<key>begin</key>
			<string>(\()</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.separator.relish</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(\))</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.separator.relish</string>
				</dict>
			</dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>$self</string>
				</dict>
			</array>
		</dict>
		<key>datatype</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>[A-Z][a-z][A-Za-z0-9]*</string>
					<key>name</key>
					<string>entity.name.function.relish</string>
				</dict>
			</array>
		</dict>
		<key>multiline_string</key>
		<dict>
			<key>begin</key>
			<string>[^"]+(""" *$)</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>string.quoted.triple.relish</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(^""" *$)</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>string.quoted.triple.relish</string>
				</dict>
			</dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>.</string>
					<key>name</key>
					<string>string.quoted.triple.relish</string>
				</dict>
			</array>
		</dict>
		<key>numeric</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>constant.numeric.relish</string>
						</dict>
					</dict>
					<key>match</key>
					<string>\b((0(x|X)[0-9a-fA-F]*)|(([0-9]+\.?[0-9]*)|(\.[0-9]+))((e|E)(\+|-)?[0-9]+)?)\b</string>
				</dict>
				<dict>
					<key>match</key>
					<string>[=\+\&lt;\&gt;\*\$/\.&amp;\|:|//|//|]</string>
					<key>name</key>
					<string>punctuation.separator.relish</string>
				</dict>
			</array>
		</dict>
		<key>string</key>
		<dict>
			<key>begin</key>
			<string>(")</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>string.quoted.double.relish</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(")</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>string.quoted.double.relish</string>
				</dict>
			</dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#string</string>
				</dict>
				<dict>
					<key>match</key>
					<string>.</string>
					<key>name</key>
					<string>string.quoted.double.relish</string>
				</dict>
			</array>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>source.relish</string>
	<key>uuid</key>
	<string>ca03e751-04ef-4330-9a6b-9b99aae1c418</string>
</dict>
</plist>
